### ISSUE TITLE
Request: method for refreshing refresh_token and setting

### ISSUE THREAD

**Issue by eggplants** [upbit/pixivpy#182]
If the `refresh_token` expires, you will get a response like the following.

```json
{
  "error": {
    "user_message": "",
    "message": "Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_grant",
    "reason": "",
    "user_message_details": {}
  }
}
```

I would like to have a method that would update the token (as shown in [this gist](https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362)) and set it a new one.

**Comment by Xdynix** [comment]
For `access_token`, we can use `refresh_token` to update it, if it expires (usually 3600 seconds). `PixivPy` imitates the requests sent by Pixiv's iOS client. Even the official Pixiv client can only ask you to log in again if the token expires. So there is no way to refresh it, you must redo the manual procedure to retrive it.

Personally, I have used the same refresh token for several months, and I even wonder if it will really expire. I think the frequency of such manual operations is acceptable. If you encounter this error frequently, then I think it's not because the token has expired.

**Comment by eggplants** [comment]
I would be willing to incorporate the following parts into Pixivpy:

https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362#file-pixiv_auth-py-L86-L97

and

https://github.com/eggplants/pixiv-bulk-downloader/blob/0f0ff6c23520d2093a6c7d41aa3e1becafae2376/pbd/base.py#L19-L23

**Comment by eggplants** [comment]
I think that the `refresh` method of `pixiv_auth.py` is relatively easy to implement in Pixivpy.

**Comment by upbit** [comment]
Try: `api.auth(refresh_token="xxx")`

**Comment by eggplants** [comment]
I didn't understand just `aapi.auth` is enough to update the access token. Thank you!
