### ISSUE TITLE
no user_bookmarks_novel() method

### ISSUE THREAD

**Issue by anguines** [upbit/pixivpy#299]
![image](https://github.com/upbit/pixivpy/assets/147581102/490d6e39-3efa-4756-8838-730790fe984e)

the method user_bookmarks_novel gives an error even after i've created the object from the AppPixivAPI class?

**Comment by Xdynix** [comment]
The `user_bookmarks_novel` is added in the latest commit 8975a075 and not yet publish to pypi. If you want to use this method, you can install pixivpy from Github repo with `pip install git+https://github.com/upbit/pixivpy`.

**Comment by upbit** [comment]
Apologies for the delay in releasing a new version.
We are currently unable to do so due to compatibility issues with urllib3, related to #286 . We are uncertain if the updates will further exacerbate this problem.

In the meantime, you can try `the command` provided above (installing from the `master` branch from GitHub), to test for compatibility.
If you encounter any issues, please feel free to provide feedback at any time.

**Comment by upbit** [comment]
Pushed: [v3.7.4](https://pypi.org/project/pixivpy3/3.7.4/)
