### ISSUE TITLE
Can't access some users' illusts

### ISSUE THREAD

**Issue by SamusAranX** [upbit/pixivpy#79]
I have a tool that randomly downloads and displays pictures, but sometimes the Pixiv API returns the following error message when calling `api.users_works`:
```json
{
  "status": "failure",
  "has_error": true,
  "errors": {
    "system": {
      "message": "登録が不完全なユーザです。",
      "code": 971
    }
  }
}
```

My tool has been running for over a year now and this is the first time I've gotten this error. Is there any way I can avoid this?

Due to the nature of the tool, user IDs aren't logged, so I can't provide an example.

**Comment by upbit** [comment]
I have not encountered a similar situation, so I can only give some advice based on my experience:

1. **Check the frequency of the login/auth API**: `access_token` has 1 hour of valid time, if you re-authenticate each time you download a picture, you may trigger a login restriction
2. **Migrate `PAPI.users_works()` to `AppAPI.user_illusts()`**: due to Public-API is deprecated, maybe the interface will be less stable, try new AppAPI for instead

I hope this will help you.

**Comment by MDeath** [comment]
Go to the author's homepage. Maybe he's banned
